### ISSUE TITLE
Migration issue in initial development workflow with vagrant

### ISSUE THREAD

**Issue by theworldbright** [aspc/mainsite#49]
```
(env)vagrant@precise64:/vagrant$ /vagrant/manage.py migrate --noinput
Traceback (most recent call last):
  File "/vagrant/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app 'django_extensions' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

**Comment by theworldbright** [comment]
Potential solution: Upgrade `django_extensions` as mentioned in https://groups.google.com/forum/#!topic/django-oscar/1c-b62VMZdw

**Comment by theworldbright** [comment]
There have been no breaking changes from 1.3.2 to 1.5.9 according to https://github.com/django-extensions/django-extensions/blob/master/CHANGELOG.md, so I went ahead and pushed this on master.
